### PR TITLE
Fix #2589

### LINKED ISSUE #2589: Performance Issues with Cartesian Axis (getStringSize)
- [ ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/s/magical-kilby-r8npx?file=/src/App.js)

### Steps to reproduce
Start a performance profile in chrome dev tools and you can see that there is a force reflow for every axis tick, which in the example is 5.

### What is expected?
the recharts render method would not utilize getStringSize because of its performance implications.

### What is actually happening?
As sample size increases and several charts are rendered on the same page the above reflow completely cripples the application performance.

| Environment | Info |
|---|---|
| Recharts | v2.0.8 |
| React | 16.8.1 |
| System | OSX and Windows |
| Browser | Chrome, Safari, and Firefox |

---
this issue was submitted previously https://github.com/recharts/recharts/issues/1465 and closed.

### PR DESCRIPTION
**Pull request by HHongSeungWoo**
## Description

While not a fundamental solution, it will better utilize caching.

## Related Issue

#2589

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] I have added a storybook story or extended an existing story to show my changes
- [x] All new and existing tests passed.

### CODE REVIEW

File: src/util/DOMUtils.ts [hunk 1]
```diff
@@ -96,13 +105,10 @@ export const getStringSize = (text: string | number, style: CSSProperties = {}):
...
-    const measurementSpanStyle: Record<string, any> = { ...SPAN_STYLE, ...style };
-    Object.keys(measurementSpanStyle).map(styleKey => {
-      (measurementSpan.style as Record<string, any>)[styleKey] = measurementSpanStyle[styleKey];
-      return styleKey;
-    });
+    const measurementSpanStyle: Record<string, any> = { ...SPAN_STYLE, ...copyStyle };
+    Object.assign(measurementSpan.style, measurementSpanStyle);
 
-    measurementSpan.textContent = str;
+    measurementSpan.textContent = `${text}`;
```
Comment (ckifer) [inline src/util/DOMUtils.ts:111]: The template literal isn't used so can probably remove in favor of just text (though ik this was here before)

File: src/util/DOMUtils.ts [hunk 2]
```diff
@@ -73,14 +73,23 @@ export const getStyleString = (style: CSSProperties) =>
     '',
   );
 
+function removeInvalidKeys(obj: Record<string, any>) {
+  const copyObj = { ...obj };
+  Object.keys(copyObj).forEach(key => {
+    if (!copyObj[key]) {
```
Comment (ckifer) [inline src/util/DOMUtils.ts:79]: I'm confused, why would this ever not be true if you just called object.keys? Only if someone passed in. A falsy value?

**Review by ckifer — CHANGES_REQUESTED** [review]

File: src/util/DOMUtils.ts (hunk 1 above)
Comment (HHongSeungWoo) [reply src/util/DOMUtils.ts:111]: need type casting if you don't convert it into a string.

File: src/util/DOMUtils.ts (hunk 2 above)
Comment (HHongSeungWoo) [reply src/util/DOMUtils.ts:79]: In functions like getTicks, we are passing undefined or an empty string to font-size.

File: src/util/DOMUtils.ts (hunk 1 above)
Comment (ckifer) [reply src/util/DOMUtils.ts:111]: It is a string right? Would `String(text)` be more appropriate?

Comment (HHongSeungWoo) [reply src/util/DOMUtils.ts:111]: That doesn't seem like a good idea in several ways. There's no need to box primitive types into objects, and it's performance-wise not optimal

Comment (ckifer) [reply src/util/DOMUtils.ts:111]: Hm, I don't like the fact that it's there 😅. But only because it wouldn't need to be there if the type was correct. Guess it's fine

**Review by ckifer — APPROVED** [review]

File: src/util/DOMUtils.ts (hunk 2 above)
Comment (nikolasrieble) [reply src/util/DOMUtils.ts:79]: Then I wonder, should we even call getStringSize in those cases?

Comment (HHongSeungWoo) [reply src/util/DOMUtils.ts:79]: It's an issue stemming from not knowing the calculated font size before the DOM is rendered. If the component waits for rendering in the DOM and calculates it all at once, the problem should be resolved. With the ongoing refactorings, it might naturally get resolved, don't you think?
