### PR TITLE
fix: missing dependency in `useEffect` in `SetPolarLegendPayload`

### LINKED ISSUE #5550: `useEffect` in `SetPolarLegendPayload` has a missing dependency
The `useEffect` array in `SetPolarLegendPayload` has a missing dependency.

### PR DESCRIPTION
**Pull request by hamirmahal**
## Description

This adds a missing dependency to the `useEffect` in `SetPolarLegendPayload`.

## Related Issue

Fixes #5550

## How Has This Been Tested?

git pre-push hook

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] I have added a storybook story or extended an existing story to show my changes

### CODE REVIEW

File: src/state/SetLegendPayload.ts [hunk 1]
```diff
@@ -1,9 +1,9 @@
 import { useEffect } from 'react';
-import { LegendPayload } from '../component/DefaultLegendContent';
-import { useAppDispatch, useAppSelector } from './hooks';
-import { addLegendPayload, removeLegendPayload } from './legendSlice';
+import type { LegendPayload } from '../component/DefaultLegendContent';
```
Comment (hamirmahal) [inline src/state/SetLegendPayload.ts:2]: This import is just used as a type.

File: src/state/SetLegendPayload.ts [hunk 2]
```diff
@@ -33,6 +33,6 @@ export function SetPolarLegendPayload({ legendPayload }: { legendPayload: Readon
     return () => {
       dispatch(removeLegendPayload(legendPayload));
     };
-  }, [dispatch, legendPayload]);
+  }, [dispatch, layout, legendPayload]);
```
Comment (ckifer) [inline src/state/SetLegendPayload.ts:36]: @PavelVanecek might have omitted this on purpose. Will wait for his review

**Review by PavelVanecek — APPROVED** [review]

File: src/state/SetLegendPayload.ts (hunk 2 above)
Comment (PavelVanecek) [reply src/state/SetLegendPayload.ts:36]: I would have left a comment if it was on purpose. Thanks for the fix

Comment (hamirmahal) [reply src/state/SetLegendPayload.ts:36]: You're welcome!
