### PR TITLE
fix(Pie): prevent cross-highlighting in multi-Pie charts with shared dataKey

### LINKED ISSUE #6259: TwoLevelPieChart with activeShape does not work as expected
## What is the current behavior?

When combining the [TwoLevelPieChart](https://recharts.org/en-US/examples/TwoLevelPieChart) example with the [CustomActiveShapePieChart](https://recharts.org/en-US/examples/CustomActiveShapePieChart) from the documentation, the detection of what pie-slice is hovered seems broken.

Image

## What is the expected behavior?

Only the hovered pie-slice's active shape should be rendered.

## Please provide a demo of the problem in a sandbox

https://stackblitz.com/edit/react-lnlglkfj-p1air5gc?file=src%2FExample.jsx

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

Recharts: 3.1.2
Chrome: 139.0.7258.155 and Firefox: 142.0.1
Windows 11

I didn't try this in a previous recharts version.

### PR DESCRIPTION
**Pull request by shreedharbhat98**
## Description

Fixed issue where multiple Pie components with the same `dataKey` would incorrectly highlight together when hovering over one of them. The fix implements graphical item ID tracking in the tooltip state infrastructure, preparing for component-specific matching to ensure each Pie chart maintains independent active states.

## Related Issue

Fixes #6259

## Motivation and Context

When rendering multiple Pie charts (e.g., concentric pies) with the same `dataKey` prop, hovering over a sector in one Pie would incorrectly activate the corresponding sector in all other Pies with the same dataKey. This happened because the active sector selection logic only matched by index and dataKey, without considering which specific graphical item (Pie component) the interaction occurred on.

This change adds the infrastructure required to allow proper independent interaction with multiple Pie charts in the same visualization, which is a common use case for two-level or nested pie charts.

## How Has This Been Tested?
1. **Type Safety**: All TypeScript type checks passing across main source, tests, storybook, and website
2. **Unit Tests**: Updated 11 test files (34+ locations) to include the new `graphicalItemId` field in tooltip state expectations
3. **Test Suite**: All 7360 tests passing, including:
   - `Pie.spec.tsx` - Comprehensive Pie component tests including tooltip interactions
   - `Tooltip.sync.spec.tsx` - Tooltip synchronization tests
   - `Tooltip.visibility.spec.tsx` - Tooltip visibility state tests
   - `useChartSynchronisation.spec.tsx` - Chart synchronization hook tests
   - All selector and state management tests
4. **Live Demo**: https://stackblitz.com/edit/react-lnlglkfj-29bjqzhg?file=src%2Findex.js

**Testing approach:**
- Verified type safety of tooltip state with new `graphicalItemId` field
- Ensured backward compatibility - existing code continues to work with `graphicalItemId: undefined`
- Validated that all tooltip state objects properly include the new field
- Confirmed no breaking changes to existing APIs|

## Screenshots (if appropriate):

Live demo available at: https://stackblitz.com/edit/react-lnlglkfj-29bjqzhg?file=src%2Findex.js

| Before | After |
|--------|--------|
|  pie | Screenshot 2025-11-23 at 8 11 06 PM |

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [ ] I have added a storybook story or VR test, or extended an existing story or VR test to show my changes

**Technical Implementation Details:**
- Added optional `dataKey` field to `PieSectorDataItem` type (non-breaking - defaults to `'value'`)
- Implemented coordinate-based matching in `PieSectors.tsx` comparing `activeCoordinate` with `sector.tooltipPosition`
- Uses 0.01 pixel tolerance to handle floating-point precision from trigonometric calculations
- Updated selector tests to include `dataKey` in sector expectations

## Summary by CodeRabbit

* **New Features**
  * Tooltip now tracks per-visual-item IDs, enabling distinct hover/click identification for overlapping or multi-layer charts.

* **Bug Fixes**
  * Corrected active/hover behavior so only the intended sector shows as active when multiple pies share data keys.

* **Tests**
  * Added and updated tests for two-level/multi-pie active-shape rendering and tooltip synchronization.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

**Comment by shreedharbhat98** [comment]
Hi @ckifer I have tried to fix the [issue](https://github.com/recharts/recharts/issues/6259) here. Feel free to take a look when you are available. 
Thanks a bunch in advance!

**Review by PavelVanecek — APPROVED** [review]

File: src/polar/Pie.tsx [hunk 1]
```diff
@@ -506,7 +513,19 @@ function PieSectors(props: PieSectorsProps) {
       {sectors.map((entry, i) => {
         if (entry?.startAngle === 0 && entry?.endAngle === 0 && sectors.length !== 1) return null;
 
-        const isActive = String(i) === activeIndex;
+        // For Pie charts, when multiple Pies share the same dataKey, we need to ensure only the hovered Pie's sector is active.
+        // We do this by checking if the active tooltip coordinate matches this sector's tooltip position.
+        // This works because each sector has a unique tooltip position based on its midAngle and middleRadius.
+        const coordinateMatches =
```
Comment (ckifer) [inline src/polar/Pie.tsx]: This will lead to issues down the road if we ever want to support Pie tooltips that are not a fixed position. I wonder if there is a way to use graphicalItemId here to identify what pie is being hovered. Can we add graphicalItemId to the active item state?

**Review by ckifer — CHANGES_REQUESTED** [review]
This might be a good interim but I don't really think this works long term - can you give a different approach a try and if it doesn't work we can merge this for now?

File: src/polar/Pie.tsx (hunk 1 above)
Comment (PavelVanecek) [reply src/polar/Pie.tsx]: +1 let's have this based on the graphical item ID.

Comment (shreedharbhat98) [reply src/polar/Pie.tsx]: @ckifer I have made the necessary changes and upadted stackblitz link as well. Please do take a look
Thanks!
