### PR TITLE
fix(z-index): prevent elements from disappearing during dynamic zIndex transitions

### LINKED ISSUE #6789: zIndex property doesn't like to be changed in quick succession
## What is the current behavior?

With slight adaptations to the Legend with Opacity example, if you hover the legend items in quick succession, curves will start disappearing from the chart (and also from the DOM). 

https://github.com/user-attachments/assets/0ae5d08c-dede-4a17-a85a-a300002e0791

It seems to happen when a dynamic zIndex is added, which leads me to believe it's a internal bug. 
The issue can be much more critical if more curves are added or more complex configuration is used, to the point where moving away from the plot does not cause the curve to be re-rendered.

*Bonus: animations seem broken like in [here](https://github.com/recharts/recharts/issues/6044)

## What is the expected behavior?

Using reactive values for zIndex should not remove data curves from the plot entirely

## Please provide a demo of the problem in a sandbox

https://stackblitz.com/edit/wzkj8wsc-otcdqw2a?file=src%2FExample.tsx

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

Haven't tested previous version., this is happening in 3.6

### PR DESCRIPTION
**Pull request by VIDHITTS**
## Description

When `zIndex` is changed dynamically (e.g., on legend hover), chart elements briefly disappear because [ZIndexLayer](cci:1://file:///Users/vidhitt.s/Desktop/recharts/src/zIndex/ZIndexLayer.tsx:43:0-150:1) returns `null` during the transition between portals.

**Root cause:** The original `useLayoutEffect` cleanup immediately calls `unregisterZIndexPortal(oldZIndex)`, which deletes the entry from Redux and removes the old `<g>` DOM node from the SVG. The new portal isn't ready yet (it requires a full render cycle through [AllZIndexPortals](cci:1://file:///Users/vidhitt.s/Desktop/recharts/src/zIndex/ZIndexPortal.tsx:21:0-43:1) → [ZIndexSvgPortal](cci:1://file:///Users/vidhitt.s/Desktop/recharts/src/zIndex/ZIndexPortal.tsx:6:0-19:1)), so `portalElement` is `undefined` and [ZIndexLayer](cci:1://file:///Users/vidhitt.s/Desktop/recharts/src/zIndex/ZIndexLayer.tsx:43:0-150:1) returns `null`.

**Fix:** Defer unregistration of old zIndex values until the new portal element becomes available. A `Set` ref tracks all registered zIndexes, and old entries are only cleaned up once the new portal is confirmed ready. During the transition, `createPortal` continues rendering into the cached old portal element.

Two effects with clear separation of concerns:
1. **Lifecycle effect** — registers new zIndex values and cleans up stale ones once the new portal element is available
2. **Unmount effect** — unregisters everything when the component is removed

## Related Issue

Fixes #6789

## Motivation and Context

Users who dynamically change `zIndex` (e.g., highlighting a line on legend hover) see chart elements vanish and not come back. This is a regression-free fix that addresses the gap in the portal lifecycle without changing any other component.

## How Has This Been Tested?

- Added [test/zIndex/DynamicZIndex.spec.tsx](cci:7://file:///Users/vidhitt.s/Desktop/recharts/test/zIndex/DynamicZIndex.spec.tsx:0:0-0:0) — renders two `<Line>` components, dynamically changes `zIndex` on one via `rerender`, and asserts both lines remain in the DOM
- All **13,908 existing tests pass** with zero regressions
- Can be verified visually using the `DynamicZIndexLineChart` website example merged in the previous PR — hover over legend items rapidly and observe lines no longer disappear

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [ ] I have added a storybook story or VR test, or extended an existing story or VR test to show my changes

## Summary by CodeRabbit

* **Bug Fixes**
  * Eliminated flicker and remount flashes when portal targets change; elements with dynamic zIndex now transition smoothly and remain stable during reordering.
  * Ensured stale layer registrations are fully cleaned up when portal rendering is toggled or components unmount, preventing leftover state.

* **Tests**
  * Added a test verifying rapid dynamic zIndex updates preserve rendered layers and do not remove or hide elements.

### CODE REVIEW

File: src/zIndex/ZIndexLayer.tsx [hunk 1]
```diff
@@ -70,41 +69,83 @@ export function ZIndexLayer({ zIndex, children }: ZIndexLayerProps) {
...
+      return;
+    }
+
+    // Register the current zIndex (idempotent — skips if already registered)
+    if (!registeredZIndexesRef.current.has(zIndex)) {
+      dispatch(registerZIndexPortal({ zIndex }));
+      registeredZIndexesRef.current.add(zIndex);
     }
-    /*
-     * Because zIndexes are dynamic (meaning, we're not working with a predefined set of layers,
```
Comment (PavelVanecek) [inline src/zIndex/ZIndexLayer.tsx:80]: Please put this comment back

Comment (VIDHITTS) [reply src/zIndex/ZIndexLayer.tsx:80]: have put back the comment

File: test/zIndex/DynamicZIndex.spec.tsx [hunk 2]
```diff
@@ -0,0 +1,65 @@
...
+    // Initial render check - wait for portal registration
+    await waitFor(() => {
+      const lines = container.querySelectorAll('.recharts-line');
+      expect(lines.length).toBe(2);
+    });
+
+    const button = getByText('Increment zIndex');
+
+    // Rapid zIndex updates should not cause lines to disappear
+    // Rapid zIndex updates should not cause lines to disappear
```
Comment (PavelVanecek) [inline test/zIndex/DynamicZIndex.spec.tsx:43]:
```suggestion
```
