### PR TITLE
Dot custom classname bug fix

### LINKED ISSUE #644: custom classname to Dot from Line
Bug

When i try to set custom class for dots from, it's not working
```javascript
<Line type="monotone" dataKey="uv" dot={{r: 6, className: 'dot-red'}} />
```

The Dots circle won't have `dot-red` className cause

### PR DESCRIPTION
**Pull request by kwolfy**
#644

### CODE REVIEW

File: src/cartesian/Line.js [hunk 1]
```diff
@@ -268,7 +268,8 @@ class Line extends Component {
     } else if (_.isFunction(option)) {
       dotItem = option(props);
     } else {
-      dotItem = <Dot {...props} className="recharts-line-dot" />;
+      const className = option.className || 'recharts-line-dot';
```
Comment (xile611) [inline src/cartesian/Line.js]: Don't use `||`, use  

```jsx
import classNames from 'classnames';

const className = classNames('recharts-line-dot', option.className);
```

**Comment by kwolfy** [comment]
Done
